name: KenkePhene Emulator Test Pipeline

on:
  workflow_dispatch:

jobs:
  test-virtual-device:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Android Emulator & Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: pixel
          disk-size: 3000M
          heap-size: 512M
          disable-animations: true
          force-avd-creation: false
          script: |
            echo "Đang kiểm tra trạng thái máy ảo..."
            adb wait-for-device
            adb shell getprop sys.boot_completed
            echo "Máy ảo đã khởi động thành công!"
